In [2]:
import os, sys, glob
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from IPython.display import display

src_path = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if src_path not in sys.path:
    sys.path.append(src_path)

from flow_features import flows_df_to_np

def prepare_single_class_data(flows_path, label):
    df = pd.read_parquet(flows_path)
    df['label'] = label
    df = df[df['packets_count'] >= 3]
    labels = df['label'].values
    features_df = df.drop(['label'], axis=1)
    features, metas = flows_df_to_np(features_df)
    return features, labels, metas


data_paths = [
    # f'./../flows/train/icsx-botnet-2014',
    # f'./../flows/test/icsx-botnet-2014',
    # f'./../flows/test/ctu-13',
    # f'./../flows/test/ctu-custom',
    f'./../flows/train/icsx-ctu-extended',
    f'./../flows/test/icsx-ctu-extended',
]

for data_path in data_paths:
    benign = pd.read_parquet(f'{data_path}/benign')
    malicious = pd.read_parquet(f'{data_path}/malicious')

    if not benign.empty:
        benign = benign[benign['packets_count'] >= 3]
    malicious = malicious[malicious['packets_count'] >= 3]

    print(f"Data path: {data_path}")

    total_samples = len(benign) + len(malicious)

    print(f"Benign size: {len(benign)}")
    print(f"Malicious size: {len(malicious)}")
    print(f"Benign percentage: {len(benign) / total_samples * 100:.2f}%")
    print(f"Malicious percentage: {len(malicious) / total_samples * 100:.2f}%")

    subclasses = [os.path.basename(x) for x in glob.glob(f'{data_path}/malicious/*') if os.path.isdir(x)]
    recall_results = {}

    subclass_size = {}
    extra_subclass_size = {}

    for subclass in subclasses:
        features, labels, meta = prepare_single_class_data(f'{data_path}/malicious/{subclass}', label=1)
        subclass_size[subclass] = len(features)

    # Convert to DataFrames and calculate percentage
    malicious_df = pd.DataFrame(
        [(subclass, count, (count / total_samples) * 100) for subclass, count in subclass_size.items()],
        columns=["Subclass", "Count", "Percentage"]
    )

    # Display tables with a title
    print("Malicious Subclasses")
    display(malicious_df.round(2))

    malicious_extra_path = f'{data_path}/malicious_extra'
    if os.path.exists(malicious_extra_path):
        extra_subclasses = [os.path.basename(x) for x in glob.glob(f'{malicious_extra_path}/*') if os.path.isdir(x)]
        for subclass in extra_subclasses:
            features, labels, meta = prepare_single_class_data(f'{malicious_extra_path}/{subclass}', label=1)
            extra_subclass_size[subclass] = len(features)

        malicious_extra_df = pd.DataFrame(
            [(subclass, count, (count / total_samples) * 100) for subclass, count in extra_subclass_size.items()],
            columns=["Subclass", "Count", "Percentage"]
        )

        print("\nMalicious Extra Subclasses")
        display(malicious_extra_df.round(2))

Data path: ./../flows/train/icsx-ctu-extended
Benign size: 222016
Malicious size: 268743
Benign percentage: 45.24%
Malicious percentage: 54.76%
Malicious Subclasses

   Subclass  Count  Percentage
0    Emotet  72097       14.69
1       IRC   2491        0.51
2      Kazy  15751        3.21
3     Neris  13843        2.82
4      RBot  38408        7.83
5  TrickBot  52768       10.75
6     Virut   1686        0.34
7  WannaCry  11700        2.38
8      Zeus  59999       12.23

Data path: ./../flows/test/icsx-ctu-extended
Benign size: 82967
Malicious size: 713245
Benign percentage: 10.42%
Malicious percentage: 89.58%
Malicious Subclasses

    Subclass   Count  Percentage
0     DonBot    2796        0.35
1     Emotet  133351       16.75
2        IRC     269        0.03
3       Kazy   40297        5.06
4      Menti    2796        0.35
5      Murlo    6050        0.76
6      Neris  134179       16.85
7    NSIS.ay     858        0.11
8       RBot   38718        4.86
9      Sogou     472        0.06
10  TrickBot  150626       18.92
11     Virut  155084       19.48
12  WannaCry    3361        0.42
13    Weasel   23994        3.01
14      Zeus   20394        2.56

Malicious Extra Subclasses

      Subclass  Count  Percentage
0   Black_hole    212        0.03
1         TBot    706        0.09
2  Zero_access    518        0.07
3         Zeus    317        0.04